server:
  port: 9003

# Database
#spring.jpa.hibernate.ddl-auto=create
spring:
  jpa:
    show-sql: false
  datasource: 
     driver-class-name: oracle.jdbc.driver.OracleDriver
     url: jdbc:oracle:thin:@127.0.0.1:1521:xe
     username: SYSTEM
     password: balian1234
  boot:
    admin:
       client:
         url: http://localhost:8887
         instance:
            management-base-url: http://localhost:9003     

# Eureka Discovery Client

eureka:
   client:
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka
         
#Metrics related configurations
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    gateway:
      enabled: true   
  endpoints:
      web:
        exposure:
          include: "*"
  metrics:
    export:
      prometheus:
        enabled: true