server:
  port: 92

# Database
#spring.jpa.hibernate.ddl-auto=create
spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource: 
#     driver-class-name: oracle.jdbc.driver.OracleDriver
#     url: jdbc:oracle:thin:@127.0.0.1:1521:xe
#     username: SYSTEM
#     password: balian1234
     driver-class-name: org.postgresql.Driver
     url: jdbc:postgresql://localhost:5432/db_cliente
     username: postgres
     password: Aforo2552019

  boot:
    admin:
       client:
         url: http://app-admin-service:8887
         instance:
            management-base-url: http://localhost:92     

# Eureka Discovery Client

eureka:
   client:
      fetch-registry: true
      serviceUrl:
         defaultZone: http://app-registro-service:8889/eureka
         
#Metrics related configurations
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    gateway:
      enabled: true   
  endpoints:
      web:
        exposure:
          include: "*"
  metrics:
    export:
      prometheus:
        enabled: true