server:
  port: 93

# Database
spring:
  data:
      mongodb:              
        uri: mongodb://admingalaxy:galaxy2023@db-mongo-service:27017/db_stock?authSource=admin
  boot:
    admin:
       client:
         url: http://app-admin-service:8887
         instance:
            management-base-url: http://localhost:93
# Eureka Discovery Client

eureka:
   client:
      fetch-registry: true
      serviceUrl:
         defaultZone: http://app-registro-service:8889/eureka
         
#

#Metrics related configurations
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    gateway:
      enabled: true   
  endpoints:
      web:
        exposure:
          include: "*"
      health:
        show-details: always
  metrics:
    export:
      prometheus:
        enabled: true