server:
  port: 91

# Database
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource: 
     driver-class-name: com.mysql.cj.jdbc.Driver
     url: jdbc:mysql://db-mysql-service:3308/AMJ060223_BD_PRODUCTOS?serverTimezone=GMT-6
     username: usu_producto
     password: 123456
     
  boot:
    admin:
       client:
         url: http://localhost:8887
         instance:
            management-base-url: http://localhost:9001
# Eureka Discovery Client

eureka:
   client:
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8889/eureka
         
#

#Metrics related configurations
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    gateway:
      enabled: true   
  endpoints:
      web:
        exposure:
          include: "*"
      health:
        show-details: always
  metrics:
    export:
      prometheus:
        enabled: true